version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 5001
    ports:
      - 5001:5001
  database:
    container_name: "database"
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=autocomplete